# Generated by Django 3.2 on 2021-05-25 15:28

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='youtube_video_link',
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_video',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True),
        ),
    ]
