# Generated by Django 3.2 on 2021-06-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogtopsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_top_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blog'),
        ),
    ]
