# Generated by Django 3.2 on 2021-05-25 16:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseFullQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=50)),
                ('question', models.TextField(max_length=500)),
                ('answer', ckeditor.fields.RichTextField()),
                ('questionId', models.TextField(max_length=100)),
                ('subvisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaPage.subvisa')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visaPage.visacategory')),
            ],
        ),
    ]
