# Generated by Django 3.2 on 2021-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0002_usefullquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullquestion',
            name='heading',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
