# Generated by Django 3.2 on 2021-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0003_alter_usefullquestion_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field1',
            field=models.CharField(blank=True, default='fas fa-dollar-sign', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field2',
            field=models.CharField(blank=True, default='fas fa-hourglass-start', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field3',
            field=models.CharField(blank=True, default='fas fa-plane-departure', max_length=100),
        ),
    ]
