# Generated by Django 3.2 on 2021-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0004_auto_20210525_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='first_field3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='font_awesome_class_name1',
            field=models.TextField(blank=True, default='fas fa-dollar-sign', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='font_awesome_class_name2',
            field=models.TextField(blank=True, default='fas fa-hourglass-start', max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofsubvisa',
            name='font_awesome_class_name3',
            field=models.TextField(blank=True, default='fas fa-plane-departure', max_length=100),
        ),
    ]
