# Generated by Django 3.2 on 2021-05-25 19:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0005_auto_20210525_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadetailsdescription',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
