# Generated by Django 3.2 on 2021-06-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaPage', '0007_visatopsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='VISA ALLIANCE', max_length=100)),
                ('address', models.TextField(blank=True, default='AUSTRALIA', max_length=50)),
            ],
        ),
    ]
