# Generated by Django 3.2 on 2021-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navFooterContent', '0002_auto_20210525_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarandfooter',
            name='footer_consultation_hyperlink',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
