# Generated by Django 3.2 on 2021-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navFooterContent', '0003_navbarandfooter_footer_consultation_hyperlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationAndMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/accred')),
            ],
        ),
        migrations.CreateModel(
            name='LegalContain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_title', models.TextField(blank=True, max_length=500)),
                ('legal_title_hyperlink', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
