# Generated by Django 3.2 on 2021-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navFooterContent', '0004_accreditationandmembership_legalcontain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImageOfAllPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/top')),
            ],
        ),
    ]
