# Generated by Django 3.2 on 2021-05-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Mission_Vision_Value_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, max_length=500)),
                ('vision', models.TextField(blank=True, max_length=500)),
                ('value', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='About_Us_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/home')),
                ('title', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Your_Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('button_name', models.CharField(blank=True, max_length=100)),
                ('button_hyperlink', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationComplexImageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('heading', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('hyperlink', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationComplexSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('sub_heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileViewSliding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('description_1', models.TextField(blank=True, max_length=200)),
                ('description_2', models.TextField(blank=True, max_length=200)),
                ('button_name', models.CharField(blank=True, max_length=100)),
                ('button_hyperlink', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Resources_Background_Image_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_Description_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('font_awesome_class_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Add_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('title', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hyperlink', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=300)),
                ('heading', models.TextField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('description_click', models.TextField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlidingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('description_1', models.TextField(blank=True, max_length=200)),
                ('description_2', models.TextField(blank=True, max_length=200)),
                ('description_3', models.TextField(blank=True, max_length=200)),
                ('button_name', models.CharField(blank=True, max_length=100)),
                ('button_hyperlink', models.TextField(blank=True, max_length=500)),
                ('qr_code', models.ImageField(upload_to='photos/home')),
                ('is_qr', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_Us_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('want_print_question', models.BooleanField(default=False)),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingPage.about_us_question')),
            ],
        ),
    ]
