# Generated by Django 3.2 on 2021-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='photos/home')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('description_1', models.TextField(blank=True, max_length=200)),
                ('description_2', models.TextField(blank=True, max_length=200)),
                ('occupation_button_name', models.CharField(blank=True, max_length=100)),
                ('occupation_button_hyperlink', models.TextField(blank=True, max_length=500)),
                ('contact_button_name', models.CharField(blank=True, max_length=100)),
                ('contact_button_hyperlink', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MobileViewSliding',
        ),
    ]
