# Generated by Django 3.2 on 2021-05-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_auto_20210525_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MigrationComplexSection',
            new_name='IIIMigrationComplexSection',
        ),
        migrations.RenameModel(
            old_name='MobileView',
            new_name='IIMobileView',
        ),
        migrations.RenameModel(
            old_name='SlidingImage',
            new_name='ISlidingImage',
        ),
        migrations.RenameModel(
            old_name='MigrationComplexImageSection',
            new_name='IVMigrationComplexImageSection',
        ),
        migrations.RenameModel(
            old_name='AfterAboutOurCompanySection',
            new_name='IXAfterAboutOurCompanySection',
        ),
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='VAboutSection',
        ),
        migrations.RenameModel(
            old_name='About_Mission_Vision_Value_Section',
            new_name='VIAbout_Mission_Vision_Value_Section',
        ),
        migrations.RenameModel(
            old_name='About_Us_Question',
            new_name='VIIAbout_Us_Question',
        ),
        migrations.RenameModel(
            old_name='About_Us_Answer',
            new_name='VIIIAbout_Us_Answer',
        ),
        migrations.RenameModel(
            old_name='Resources_Description_Section',
            new_name='XIIIResources_Description_Section',
        ),
        migrations.RenameModel(
            old_name='Resources_Background_Image_Section',
            new_name='XIIResources_Background_Image_Section',
        ),
        migrations.RenameModel(
            old_name='Service_Add_Section',
            new_name='XIService_Add_Section',
        ),
        migrations.RenameModel(
            old_name='Service_Section',
            new_name='XService_Section',
        ),
    ]
