# Generated by Django 3.2 on 2021-05-23 07:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=50)),
                ('title_2', models.CharField(blank=True, max_length=50)),
                ('description_1', models.TextField(blank=True, max_length=150)),
                ('description_2', models.TextField(blank=True, max_length=150)),
                ('heading', models.CharField(blank=True, max_length=20)),
                ('heading_description', ckeditor.fields.RichTextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='photos/about')),
                ('background_image', models.ImageField(blank=True, upload_to='photos/about')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('card_side_image', models.ImageField(blank=True, upload_to='photos/about')),
                ('core_title', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('font_awesome_class_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'CompanyQuality',
                'verbose_name_plural': 'CompanyQualities',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/about')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TopAboutUsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/blog')),
                ('description', models.TextField(default='About Us', max_length=100)),
            ],
        ),
    ]
